import React from 'react';
export const metadata = {
    title: 'all doctors',
    description: 'Generated by create next app',
  }

const Alldoctor = () => {
    return (
        <div>
            all doctor
        </div>
    );
};

export default Alldoctor;